# https://docs.microsoft.com/azure/devops/pipelines/languages/android
pool:
  vmImage: 'macOS-latest'

steps:

# Download secure file
# Download a secure file to the agent machine
- task: DownloadSecureFile@1
  name: mySecureFile # The name with which to reference the secure file's path on the agent, like $(mySecureFile.secureFilePath)
  inputs:
    secureFile: apikey.properties # The file name or GUID of the secure file
    #retryCount: 5 # Optional

- task: CopyFiles@2
  inputs:
    contents: '$(mySecureFile.secureFilePath)/apikey.properties'
    targetFolder: $(Agent.BuildDirectory)

- task: Gradle@2
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    publishJUnitResults: true
    testResultsFiles: '**/testDebugUnitTest/TEST-*.xml'
    tasks: 'build'

- task: CopyFiles@2
  inputs:
    contents: '**/*.apk'
    targetFolder: '$(build.artifactStagingDirectory)'

- task: PublishBuildArtifacts@1

- task: GitHubRelease@0
  displayName: 'GitHub release (create)'
  inputs:
    gitHubConnection: github/ratanparai
    assets: '$(build.artifactStagingDirectory)/**/*.apk'